name: Build & Release Windows EXE

on:
  push:
    tags:
      - 'v*'  # Run only on version tags like v1.0.0

jobs:
  build:
    name: Build Windows .exe
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Build Windows EXE
        run: flutter build windows

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/x64/runner/Release/dns_switcher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
